name: Include/don't include a project
description: Provide information about a project to be added to awesome-connect-iq list or a project that shouldn't be included.
title: "Project proposal: ..."
labels: ["needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Please, note, that this issue type is about a project (Watch App, Widget, etc.), not learning materials (tutorial, video, etc.).
        The latter has its own issue type. <<TODO: Add link>>  
  - type: markdown
    attributes:
      value: |
        # Summary

        Provide information about a project to be added to awesome-connect-iq list or a project that shouldn't be included.
  - type: dropdown
    id: decision
    attributes:
      label: Decision
      description: Is this PR for including a project in the list, or not including the project?
      options:
        - Include
        - Do not include
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Justification
      description: Include some summary, why the project should be accepted/rejected.
      placeholder: Tell us what you think!
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Information about the project

  - type: input
    id: projectUrl
    attributes:
      label: Repo URL
      description: "Provide valid URL of the project's repository"
      placeholder: "..."
    validations:
      required: true

  - type: dropdown
    id: projectType
    attributes:
      label: What is the project type?
      multiple: true
      options:
        - Watch Face
        - Device App
        - Data Field
        - Widget
        - Audio Content Provider
        - Collection
        - Unknown
    validations:
      required: true

  - type: dropdown
    id: license
    attributes:
      label: What is the project license?
      multiple: false
      options:
        - Apache-2.0
        - MIT
        - Some
        - Other (describe in "Jaustification")
        - Unknown

  - type: input
    id: appstoreUrl
    attributes:
      label: Connect IQ Store URL
      description: "If the project (app/watch face, etc.) is published in the app store, provide a link."
      placeholder: "https://apps.garmin.com/en-US/"

  - type: input
    id: simulator
    attributes:
      label: Tested in the simulator?
      description: "Does it run in the simulator?	Yes/no. Which device?"
      placeholder: "Fenix 5"
    validations:
      required: false
  - type: input
    id: device
    attributes:
      label: Tested on an actual device?
      description: Does it run on a device?	Yes/no. Which device?
      placeholder: "Fenix 5"
    validations:
      required: false

  - type: checkboxes
    id: sourcecode
    attributes:
      label: Quality of the code?
      description: You may select more than one.
      options:
        - label: Clean code
        - label: Good README/docs

  - type: textarea
    id: description
    attributes:
      label: Description of the project
      description: What does it actually do? What are the key learnings from analyzing the project (programming techniques/mechanics).
      placeholder: Tell us what you think!
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional info
      description: Include some summary, why the project should be accepted/rejected.
      placeholder: Tell us what you think!
