name: verifier-workflow

on:
  issues:
    types:
      - opened

jobs:
  verifier:
    runs-on: ubuntu-latest
    steps:
      - name: alla
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.issue) }}
        run: |
          ls -la
    - name:
        Do something
      run: |
        echo "the end"